### ISSUE TITLE
Remove display cutout in Android.

### ISSUE THREAD

**Issue by sheesh3178** [neil4/RetroArch-Lite#2]
You know that black spare space on the left side when landscape or on the upper side when portrait? It would be nice to have that gone. The official Retroarch build already has an option to remove that.

**Comment by neil4** [comment]
Is this the "fullscreen over notch" setting in retroarch?  I'll add it if you're willing to test it.  I don't have any devices with a camera cutout.

**Comment by sheesh3178** [comment]
> Is this the "fullscreen over notch" setting in retroarch? I'll add it if you're willing to test it. I don't have any devices with a camera cutout.

Yes.

**Comment by neil4** [comment]
Thanks. I'll get you a build next weekend, most likely. Out of town until then

**Comment by neil4** [comment]
@sheesh3178 Ok, [here](https://drive.google.com/drive/folders/1e8UrGvRtBmypTrF0n0lFzwTSOI5SuPUo?usp=drive_link) it is. The new option is in the "A/V" tab of the launcher's settings, defaulted to on.

**Comment by sheesh3178** [comment]
Thanks! It works.

**Comment by neil4** [comment]
Cool. Making it official
