### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by master1274** [neil4/RetroArch-Lite#3]
Hello developer. At the moment in this project, while the game is running, I only see the opportunity to change the game and completely exit RetroArch Lite. Maybe I'm not paying attention. I would like to be able to close the current content along with the core, and be in the interface RetroArch Lite. To be able to choose emulation of other gaming equipment.

**Comment by neil4** [comment]
That's intentional, but having an option to return to the launcher might be good.

**Comment by neil4** [comment]
That means implemented!
